/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as doctorManagementSol from "./DoctorManagement.sol";
export type { doctorManagementSol };
import type * as researcherManagementSol from "./ResearcherManagement.sol";
export type { researcherManagementSol };
export type { PatientDataManagement } from "./PatientDataManagement";
