/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as inheritanceSol from "./Inheritance.sol";
export type { inheritanceSol };
export type { BookStore } from "./BookStore";
export type { Boolean } from "./Boolean";
export type { ErrorHandling } from "./ErrorHandling";
export type { Events } from "./Events";
export type { Example } from "./Example";
export type { GetNumber } from "./GetNumber";
export type { Mapping } from "./Mapping";
export type { Modifiers } from "./Modifiers";
export type { PatientDataManagement } from "./PatientDataManagement";
export type { String } from "./String";
export type { Uint } from "./Uint";
