/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPatientDataManagement } from "./IPatientDataManagement";
export type { ResearcherManagement } from "./ResearcherManagement";
