/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPatientDataManagementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAnonymizedPatientData"
      | "grantResearcherAccess"
      | "revokeResearcherAccess"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAnonymizedPatientData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantResearcherAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeResearcherAccess",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAnonymizedPatientData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantResearcherAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeResearcherAccess",
    data: BytesLike
  ): Result;
}

export interface IPatientDataManagement extends BaseContract {
  connect(runner?: ContractRunner | null): IPatientDataManagement;
  waitForDeployment(): Promise<this>;

  interface: IPatientDataManagementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAnonymizedPatientData: TypedContractMethod<[], [string], "view">;

  grantResearcherAccess: TypedContractMethod<
    [_researcher: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeResearcherAccess: TypedContractMethod<
    [_researcher: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAnonymizedPatientData"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "grantResearcherAccess"
  ): TypedContractMethod<[_researcher: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeResearcherAccess"
  ): TypedContractMethod<[_researcher: AddressLike], [void], "nonpayable">;

  filters: {};
}
