/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPatientDataManagement__factory } from "./IPatientDataManagement__factory";
export { ResearcherManagement__factory } from "./ResearcherManagement__factory";
