/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Boolean, BooleanInterface } from "../../contracts/Boolean";

const _abi = [
  {
    inputs: [],
    name: "returnVotingState",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "_state",
        type: "bool",
      },
    ],
    name: "setVotingState",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610171806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063698b21351461003b578063bfd41f3b14610059575b600080fd5b610043610075565b60405161005091906100f8565b60405180910390f35b610073600480360381019061006e91906100bc565b61008b565b005b60008060009054906101000a900460ff16905090565b806000806101000a81548160ff02191690831515021790555050565b6000813590506100b681610124565b92915050565b6000602082840312156100d2576100d161011f565b5b60006100e0848285016100a7565b91505092915050565b6100f281610113565b82525050565b600060208201905061010d60008301846100e9565b92915050565b60008115159050919050565b600080fd5b61012d81610113565b811461013857600080fd5b5056fea26469706673582212203db695cd0f6fde5a5e5d4c0b4fc90a760e630cb70ef021611e7a55f9dc4b3f4264736f6c63430008070033";

type BooleanConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BooleanConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Boolean__factory extends ContractFactory {
  constructor(...args: BooleanConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Boolean & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Boolean__factory {
    return super.connect(runner) as Boolean__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BooleanInterface {
    return new Interface(_abi) as BooleanInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Boolean {
    return new Contract(address, _abi, runner) as unknown as Boolean;
  }
}
