/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as inheritanceSol from "./Inheritance.sol";
export { BookStore__factory } from "./BookStore__factory";
export { Boolean__factory } from "./Boolean__factory";
export { ErrorHandling__factory } from "./ErrorHandling__factory";
export { Events__factory } from "./Events__factory";
export { Example__factory } from "./Example__factory";
export { GetNumber__factory } from "./GetNumber__factory";
export { Mapping__factory } from "./Mapping__factory";
export { Modifiers__factory } from "./Modifiers__factory";
export { PatientDataManagement__factory } from "./PatientDataManagement__factory";
export { String__factory } from "./String__factory";
export { Uint__factory } from "./Uint__factory";
