/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as doctorManagementSol from "./DoctorManagement.sol";
export * as researcherManagementSol from "./ResearcherManagement.sol";
export { PatientDataManagement__factory } from "./PatientDataManagement__factory";
