/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Constructor } from "./Constructor";
export type { ConstructorExample } from "./ConstructorExample";
