/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DoctorManagement } from "./DoctorManagement";
export type { IPatientDataManagement } from "./IPatientDataManagement";
