/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPatientDataManagementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPatientRecord"
      | "grantDoctorAccess"
      | "revokeDoctorAccess"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPatientRecord",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantDoctorAccess",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDoctorAccess",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPatientRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantDoctorAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDoctorAccess",
    data: BytesLike
  ): Result;
}

export interface IPatientDataManagement extends BaseContract {
  connect(runner?: ContractRunner | null): IPatientDataManagement;
  waitForDeployment(): Promise<this>;

  interface: IPatientDataManagementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPatientRecord: TypedContractMethod<
    [_patient: AddressLike],
    [string],
    "view"
  >;

  grantDoctorAccess: TypedContractMethod<
    [_doctor: AddressLike, _patient: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeDoctorAccess: TypedContractMethod<
    [_doctor: AddressLike, _patient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPatientRecord"
  ): TypedContractMethod<[_patient: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantDoctorAccess"
  ): TypedContractMethod<
    [_doctor: AddressLike, _patient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeDoctorAccess"
  ): TypedContractMethod<
    [_doctor: AddressLike, _patient: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
