// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neastjmxasengxoztkqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lYXN0am14YXNlbmd4b3p0a3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzYwMjcsImV4cCI6MjA1NjkxMjAyN30.PPyfnZw_SPWBgERvJ7K8_FrbLT99H76DxwPMMpt9Ge0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);