/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ExampleInterface extends Interface {
  getFunction(
    nameOrSignature: "returnVotingState" | "setVotingState"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "returnVotingState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVotingState",
    values: [boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "returnVotingState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotingState",
    data: BytesLike
  ): Result;
}

export interface Example extends BaseContract {
  connect(runner?: ContractRunner | null): Example;
  waitForDeployment(): Promise<this>;

  interface: ExampleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  returnVotingState: TypedContractMethod<[], [boolean], "view">;

  setVotingState: TypedContractMethod<[_state: boolean], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "returnVotingState"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setVotingState"
  ): TypedContractMethod<[_state: boolean], [void], "nonpayable">;

  filters: {};
}
