/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Child__factory } from "./Child__factory";
export { Inheritance__factory } from "./Inheritance__factory";
