/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  GetNumber,
  GetNumberInterface,
} from "../../../contracts/GetNumber.sol/GetNumber";

const _abi = [
  {
    inputs: [],
    name: "getSquare",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "num",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_num",
        type: "uint256",
      },
    ],
    name: "setNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101fd806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80633fb5c1cb146100465780634e70b1dc146100625780638dbbe62514610080575b600080fd5b610060600480360381019061005b91906100ff565b61009e565b005b61006a6100a8565b604051610077919061013b565b60405180910390f35b6100886100ae565b604051610095919061013b565b60405180910390f35b8060008190555050565b60005481565b600080546000546100bf9190610185565b905090565b600080fd5b6000819050919050565b6100dc816100c9565b81146100e757600080fd5b50565b6000813590506100f9816100d3565b92915050565b600060208284031215610115576101146100c4565b5b6000610123848285016100ea565b91505092915050565b610135816100c9565b82525050565b6000602082019050610150600083018461012c565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b6000610190826100c9565b915061019b836100c9565b92508282026101a9816100c9565b915082820484148315176101c0576101bf610156565b5b509291505056fea26469706673582212203ef628eb0ac4e9275be585c38f8ff98324969aa47b088ef4f76e4918ede133bc64736f6c63430008170033";

type GetNumberConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GetNumberConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GetNumber__factory extends ContractFactory {
  constructor(...args: GetNumberConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      GetNumber & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): GetNumber__factory {
    return super.connect(runner) as GetNumber__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GetNumberInterface {
    return new Interface(_abi) as GetNumberInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): GetNumber {
    return new Contract(address, _abi, runner) as unknown as GetNumber;
  }
}
