/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GetNumber__factory } from "./GetNumber__factory";
export { NumberStorage__factory } from "./NumberStorage__factory";
