/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type { Uint, UintInterface } from "../../../contracts/Uint.sol/Uint";

const _abi = [
  {
    inputs: [],
    name: "answer",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052600a600055600760015534801561001a57600080fd5b5061012a8061002a6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806385bb7d6914602d575b600080fd5b60336047565b604051603e91906073565b60405180910390f35b60006001546000546057919060bb565b905090565b6000819050919050565b606d81605c565b82525050565b6000602082019050608660008301846066565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b600060c482605c565b915060cd83605c565b925082820260d981605c565b9150828204841483151760ed5760ec608c565b5b509291505056fea2646970667358221220d95d456ea625fe1b092abcffa9c1ad9ca067fbd608ced6b098b03ef1c6cad54964736f6c63430008170033";

type UintConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UintConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Uint__factory extends ContractFactory {
  constructor(...args: UintConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Uint & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Uint__factory {
    return super.connect(runner) as Uint__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UintInterface {
    return new Interface(_abi) as UintInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Uint {
    return new Contract(address, _abi, runner) as unknown as Uint;
  }
}
